# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.hostname = "phusion"

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "http://halley/vagrant-images/sb-centos7-vanilla-v1-vbox"
  config.vbguest.auto_update = false

  config.vm.network :forwarded_port, guest: 80, host: 8000 # Apache
  config.vm.network :forwarded_port, guest: 8080, host: 8080 # Tomcat


  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 4
  end

  config.vm.synced_folder ".", "/vagrant", disabled: false
  config.vm.synced_folder "../", "/app", disabled: false

  config.vm.provision :shell, :name=> "040fcrepo.sh", :path => "040fcrepo.sh", :privileged => false
  config.vm.provision :shell, :name=> "300ruby.sh", :path => "300ruby.sh", :privileged => false
  config.vm.provision :shell, :name=> "400passenger.sh", :path => "400passenger.sh", :privileged => false


  config.vm.provision :shell, :name=> "600app-env.sh", :path => "600app-env.sh", :privileged => false
  config.vm.provision :shell, :name=> "700app-apache.sh", :path => "700app-apache.sh", :privileged => false

end
